---
apiVersion: v1
kind: Secret
metadata:
  name: multiclusterhub-operator-pull-secret
  namespace: open-cluster-management-observability
data:
  .dockerconfigjson: >-
    {{ ocm_pull_secret }}
type: kubernetes.io/dockerconfigjson
...